erpnext

diff --git a/docker-compose.yaml b/docker-compose.yaml
--- a/docker-compose.yaml
+++ b/docker-compose.yaml
@@ -1008,71 +1008,71 @@ services:
       - sites:/home/frappe/frappe-bench/sites
       - ${DOCKER_DIR}/finance_stack/erpnext/logs:/home/frappe/frappe-bench/logs
 
-  erpnext-configurator:
-    image: frappe/erpnext:${ERPNEXT_VERSION}
-    container_name: erpnext-configurator
-    deploy:
-      restart_policy:
-        condition: none
-    networks:
-      - finance
-    entrypoint:
-      - bash
-      - -c
-    # add redis_socketio for backward compatibility
-    command:
-      - >
-        ls -1 apps > sites/apps.txt;
-        bench set-config -g db_host $$DB_HOST;
-        bench set-config -gp db_port $$DB_PORT;
-        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
-        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
-        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
-        bench set-config -gp socketio_port $$SOCKETIO_PORT;
-    environment:
-      - DB_HOST=mariadb
-      - DB_PORT=3306
-      - REDIS_CACHE=erpnext-redis-cache:6379
-      - REDIS_QUEUE=erpnext-redis-queue:6379
-      - SOCKETIO_PORT=9000
-    volumes:
-      - sites:/home/frappe/frappe-bench/sites
-      - ${DOCKER_DIR}/finance_stack/erpnext/logs:/home/frappe/frappe-bench/logs
+  # erpnext-configurator:
+  #   image: frappe/erpnext:${ERPNEXT_VERSION}
+  #   container_name: erpnext-configurator
+  #   deploy:
+  #     restart_policy:
+  #       condition: none
+  #   networks:
+  #     - finance
+  #   entrypoint:
+  #     - bash
+  #     - -c
+  #   # add redis_socketio for backward compatibility
+  #   command:
+  #     - >
+  #       ls -1 apps > sites/apps.txt;
+  #       bench set-config -g db_host $$DB_HOST;
+  #       bench set-config -gp db_port $$DB_PORT;
+  #       bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+  #       bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+  #       bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+  #       bench set-config -gp socketio_port $$SOCKETIO_PORT;
+  #   environment:
+  #     - DB_HOST=mariadb
+  #     - DB_PORT=3306
+  #     - REDIS_CACHE=erpnext-redis-cache:6379
+  #     - REDIS_QUEUE=erpnext-redis-queue:6379
+  #     - SOCKETIO_PORT=9000
+  #   volumes:
+  #     - sites:/home/frappe/frappe-bench/sites
+  #     - ${DOCKER_DIR}/finance_stack/erpnext/logs:/home/frappe/frappe-bench/logs
 
-  erpnext-create:
-    image: frappe/erpnext:${ERPNEXT_VERSION}
-    container_name: erpnext-create
-    deploy:
-      restart_policy:
-        condition: none
-    networks:
-      - finance
-    volumes:
-      - sites:/home/frappe/frappe-bench/sites
-      - ${DOCKER_DIR}/finance_stack/erpnext/logs:/home/frappe/frappe-bench/logs
-    entrypoint:
-      - bash
-      - -c
-    command:
-      - >
-        wait-for-it -t 120 mariadb:3306;
-        wait-for-it -t 120 erpnext-redis-cache:6379;
-        wait-for-it -t 120 erpnext-redis-queue:6379;
-        export start=`date +%s`;
-        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
-          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
-          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
-        do
-          echo "Waiting for sites/common_site_config.json to be created";
-          sleep 5;
-          if (( `date +%s`-start > 120 )); then
-            echo "could not find sites/common_site_config.json with required keys";
-            exit 1
-          fi
-        done;
-        echo "sites/common_site_config.json found";
-        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=ByDzGAfhcU7hOK6YgIVfpDXWph8Kf53H --install-app erpnext --set-default demo.enext.duckdns.org;
-        bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=ByDzGAfhcU7hOK6YgIVfpDXWph8Kf53H --install-app erpnext slewa.enext.duckdns.org;
+  # erpnext-create:
+  #   image: frappe/erpnext:${ERPNEXT_VERSION}
+  #   container_name: erpnext-create
+  #   deploy:
+  #     restart_policy:
+  #       condition: none
+  #   networks:
+  #     - finance
+  #   volumes:
+  #     - sites:/home/frappe/frappe-bench/sites
+  #     - ${DOCKER_DIR}/finance_stack/erpnext/logs:/home/frappe/frappe-bench/logs
+  #   entrypoint:
+  #     - bash
+  #     - -c
+  #   command:
+  #     - >
+  #       wait-for-it -t 120 mariadb:3306;
+  #       wait-for-it -t 120 erpnext-redis-cache:6379;
+  #       wait-for-it -t 120 erpnext-redis-queue:6379;
+  #       export start=`date +%s`;
+  #       until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+  #         [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+  #         [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+  #       do
+  #         echo "Waiting for sites/common_site_config.json to be created";
+  #         sleep 5;
+  #         if (( `date +%s`-start > 120 )); then
+  #           echo "could not find sites/common_site_config.json with required keys";
+  #           exit 1
+  #         fi
+  #       done;
+  #       echo "sites/common_site_config.json found";
+  #       bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=ByDzGAfhcU7hOK6YgIVfpDXWph8Kf53H --install-app erpnext --set-default demo.enext.duckdns.org;
+  #       bench new-site --no-mariadb-socket --admin-password=admin --db-root-password=ByDzGAfhcU7hOK6YgIVfpDXWph8Kf53H --install-app erpnext slewa.enext.duckdns.org;
 
   erpnext:
     image: frappe/erpnext:${ERPNEXT_VERSION}
